# -*- coding: utf-8 -*-
"""streamlit_macro_food_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u5b8u7FAr0pvNXjLVYfKgY5ThpZ_OXl2
"""

import streamlit as st

# v0 BMR function 123

# Set title that appears in the Browser tab bar
st.set_page_config(
    page_title='BMR Calculator',
    layout="centered"
)

# Function to calculate Basal Metabolic Rate (BMR)
def calculate_bmr(age, gender, height, weight):
    """
    Calculates the Basal Metabolic Rate (BMR) using the Mifflin-St Jeor equation.
    """
    if gender == "Female":
        bmr = (10 * weight) + (6.25 * height) - (5 * age) - 161
    else:  # Male
        bmr = (10 * weight) + (6.25 * height) - (5 * age) + 5

    return bmr

# Session State Initialization
# We use session state to store the BMR value.
if 'bmr' not in st.session_state:
    st.session_state.bmr = 0

# Streamlit App Layout
st.title('Basal Metabolic Rate (BMR) Calculator')
st.markdown("Enter your details below to estimate the number of calories your body burns at rest.")

# Columns for input layout
col1, col2 = st.columns(2)
with col1:
    age = st.number_input('Age (years)', min_value=1, max_value=120, value=30)
    height = st.number_input('Height (cm)', min_value=100, max_value=250, value=170)
with col2:
    gender = st.radio('Gender', ['Male', 'Female'])
    weight = st.number_input('Weight (kg)', min_value=30.0, max_value=250.0, value=70.0)

# Button to trigger calculation
if st.button('Calculate BMR'):
    st.session_state.bmr = calculate_bmr(age, gender, height, weight)
    st.success("BMR calculation complete!")

# Display result after the button has been clicked and a value is present
if st.session_state.bmr > 0:
    st.subheader('Your Calculated BMR')
    st.metric("Basal Metabolic Rate (BMR)", f"{st.session_state.bmr:,.0f} kcal")